### ISSUE TITLE
`waitForReact()` does not correctly wait

### ISSUE THREAD

**Issue by bud-mo** [abhinaba1080/protractor-react-selector#10]
I noticed the `waitForReact()` does not wait for the timeout.

I created an example repository at https://github.com/bud-mo/react-protractor-example

The react code is initialized with a delay, simultated but can be a lazy-load of a webpack chunk.

```javascript
import React from 'react';
import { render } from 'react-dom';

window.addEventListener('load', () => {
    setTimeout(() => {
       /* This render is not considered */
        render(
            <MyComponent />,
            document.getElementById('app')
        );
    }, 100);
});

function MyComponent() {
    return (
        <div>
            Hello world!
        </div>
    );
}
```

Running the test it fails immediately without waiting the 10s timeout given.
This is the error:
```
Failures:
1) Load page Wait for react
  Message:
    Failed: javascript error: Could not find instance of React in given element
      (Session info: chrome=83.0.4103.61)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'michele', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1081-oem', java.version: '1.8.0_252'
    Driver info: driver.version: unknown
  Stack:
    JavascriptError: javascript error: Could not find instance of React in given element
      (Session info: chrome=83.0.4103.61)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'michele', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1081-oem', java.version: '1.8.0_252'
    Driver info: driver.version: unknown
        at Object.checkLegacyResponse (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/error.js:546:15)
        at parseHttpResponse (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/http.js:509:13)
        at doSend.then.response (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/http.js:441:30)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    From: Task: WebDriver.executeScript()
        at thenableWebDriverProxy.schedule (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
        at thenableWebDriverProxy.executeScript (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/webdriver.js:878:16)
        at /home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/by.js:191:35
        at call (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/webdriver.js:1068:28)
        at /home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/webdriver.js:907:19
        at ManagedPromise.invokeCallback_ (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:1376:14)
        at TaskQueue.execute_ (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:2974:25)
        at /home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:668:7
    From: Task: WebDriver.call(function)
        at thenableWebDriverProxy.call (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/webdriver.js:901:23)
        at thenableWebDriverProxy.findElementsInternal_ (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/webdriver.js:1068:17)
        at thenableWebDriverProxy.findElements (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/webdriver.js:1043:19)
        at Object.findElementsOverride (/home/michele/Progetti/altro/react-protractor-example/node_modules/protractor/built/locators.js:79:35)
        at ptor.waitForAngular.then (/home/michele/Progetti/altro/react-protractor-example/node_modules/protractor/built/element.js:156:40)
        at ManagedPromise.invokeCallback_ (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:1376:14)
        at TaskQueue.execute_ (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:2927:27)
        at /home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:668:7
    From: Task: <anonymous>
        at pollCondition (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:2195:19)
        at /home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:2191:7
        at new ManagedPromise (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:1077:7)
        at ControlFlow.promise (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:2505:12)
        at /home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:2190:22
        at TaskQueue.execute_ (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:2974:25)
        at /home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:668:7
        at process._tickCallback (internal/process/next_tick.js:68:7)
    From: Task: <anonymous wait>
        at scheduleWait (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:2188:20)
        at ControlFlow.wait (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/promise.js:2517:12)
        at thenableWebDriverProxy.wait (/home/michele/Progetti/altro/react-protractor-example/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
        at run (/home/michele/Progetti/altro/react-protractor-example/node_modules/protractor/built/browser.js:58:33)
        at ProtractorBrowser.to.(anonymous function) [as wait] (/home/michele/Progetti/altro/react-protractor-example/node_modules/protractor/built/browser.js:66:16)
        at UserContext.<anonymous> (/home/michele/Progetti/altro/react-protractor-example/e2e/specs/example_spec.js:8:17)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    From: Task: Run it("Wait for react") in control flow
        at UserContext.<anonymous> (/home/michele/Progetti/altro/react-protractor-example/node_modules/jasminewd2/index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/home/michele/Progetti/altro/react-protractor-example/e2e/specs/example_spec.js:5:2)
        at Object.<anonymous> (/home/michele/Progetti/altro/react-protractor-example/e2e/specs/example_spec.js:3:1)
        at Module._compile (internal/modules/cjs/loader.js:778:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

1 spec, 1 failure
```

**Comment by abhinaba-ghosh** [comment]
Hi @bud-mo , thanks for bringing up this pain point. 
Mounting react app asynchronously is a very rare event. I do believe, people still want to do that if react is a subset technology. Unfortunately, there is no out-of-the-box support for this issue from this library.

You need to explicitly wait for the app to be visible and then run the script ```waitForReact```. Just for a note, ```waitForReact``` also loads ```resq``` script in the window, so, you need to call it before you use ```by.react``` selector. 

So, I have updated the test script as:

```js
describe('Load page', function () {
  it('Wait for react', async function () {
    await browser.get('http://localhost:8080/');
    await browser.wait(
      until.visibilityOf(
        element(by.css('#app')),
        5000
      )
    );
    await browser.waitForReact(1000, '#app');
    expect(element(by.react('MyComponent')).isPresent()).toBeTruthy();
  });
});

```
PR id is here https://github.com/bud-mo/react-protractor-example/pull/1

This is executing every time without error. I will bring up this point in the readme in the next release. 
Let me know if this solves your issue.

**Comment by bud-mo** [comment]
I have done a refactor to load React sooner as possible. For now is ok but in the future if the core of the app will be too heavy (code splitting is already used) I will return on this point.
